// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/fkrhykal/outbox-cdc/internal/inventory/entity"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// FindByIDLockForUpdate provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) FindByIDLockForUpdate(ctx context.Context, ID uuid.UUID) (*entity.Product, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDLockForUpdate")
	}

	var r0 *entity.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Product, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Product); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_FindByIDLockForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDLockForUpdate'
type MockProductRepository_FindByIDLockForUpdate_Call struct {
	*mock.Call
}

// FindByIDLockForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockProductRepository_Expecter) FindByIDLockForUpdate(ctx interface{}, ID interface{}) *MockProductRepository_FindByIDLockForUpdate_Call {
	return &MockProductRepository_FindByIDLockForUpdate_Call{Call: _e.mock.On("FindByIDLockForUpdate", ctx, ID)}
}

func (_c *MockProductRepository_FindByIDLockForUpdate_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockProductRepository_FindByIDLockForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_FindByIDLockForUpdate_Call) Return(product *entity.Product, err error) *MockProductRepository_FindByIDLockForUpdate_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepository_FindByIDLockForUpdate_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (*entity.Product, error)) *MockProductRepository_FindByIDLockForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindWithLimit provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) FindWithLimit(ctx context.Context, limit int) ([]entity.Product, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindWithLimit")
	}

	var r0 []entity.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]entity.Product, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []entity.Product); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_FindWithLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindWithLimit'
type MockProductRepository_FindWithLimit_Call struct {
	*mock.Call
}

// FindWithLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockProductRepository_Expecter) FindWithLimit(ctx interface{}, limit interface{}) *MockProductRepository_FindWithLimit_Call {
	return &MockProductRepository_FindWithLimit_Call{Call: _e.mock.On("FindWithLimit", ctx, limit)}
}

func (_c *MockProductRepository_FindWithLimit_Call) Run(run func(ctx context.Context, limit int)) *MockProductRepository_FindWithLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_FindWithLimit_Call) Return(products []entity.Product, err error) *MockProductRepository_FindWithLimit_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockProductRepository_FindWithLimit_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]entity.Product, error)) *MockProductRepository_FindWithLimit_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStock provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) UpdateStock(ctx context.Context, product *entity.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepository_UpdateStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStock'
type MockProductRepository_UpdateStock_Call struct {
	*mock.Call
}

// UpdateStock is a helper method to define mock.On call
//   - ctx context.Context
//   - product *entity.Product
func (_e *MockProductRepository_Expecter) UpdateStock(ctx interface{}, product interface{}) *MockProductRepository_UpdateStock_Call {
	return &MockProductRepository_UpdateStock_Call{Call: _e.mock.On("UpdateStock", ctx, product)}
}

func (_c *MockProductRepository_UpdateStock_Call) Run(run func(ctx context.Context, product *entity.Product)) *MockProductRepository_UpdateStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Product
		if args[1] != nil {
			arg1 = args[1].(*entity.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_UpdateStock_Call) Return(err error) *MockProductRepository_UpdateStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepository_UpdateStock_Call) RunAndReturn(run func(ctx context.Context, product *entity.Product) error) *MockProductRepository_UpdateStock_Call {
	_c.Call.Return(run)
	return _c
}
