// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/fkrhykal/outbox-cdc/internal/inventory/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReservationRepository creates a new instance of MockReservationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationRepository {
	mock := &MockReservationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReservationRepository is an autogenerated mock type for the ReservationRepository type
type MockReservationRepository struct {
	mock.Mock
}

type MockReservationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationRepository) EXPECT() *MockReservationRepository_Expecter {
	return &MockReservationRepository_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type MockReservationRepository
func (_mock *MockReservationRepository) Save(ctx context.Context, itemReservation *entity.Reservation) error {
	ret := _mock.Called(ctx, itemReservation)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Reservation) error); ok {
		r0 = returnFunc(ctx, itemReservation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReservationRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockReservationRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - itemReservation *entity.Reservation
func (_e *MockReservationRepository_Expecter) Save(ctx interface{}, itemReservation interface{}) *MockReservationRepository_Save_Call {
	return &MockReservationRepository_Save_Call{Call: _e.mock.On("Save", ctx, itemReservation)}
}

func (_c *MockReservationRepository_Save_Call) Run(run func(ctx context.Context, itemReservation *entity.Reservation)) *MockReservationRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Reservation
		if args[1] != nil {
			arg1 = args[1].(*entity.Reservation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservationRepository_Save_Call) Return(err error) *MockReservationRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReservationRepository_Save_Call) RunAndReturn(run func(ctx context.Context, itemReservation *entity.Reservation) error) *MockReservationRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
