// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package data

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTxContext creates a new instance of MockTxContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxContext[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxContext[T] {
	mock := &MockTxContext[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxContext is an autogenerated mock type for the TxContext type
type MockTxContext[T any] struct {
	mock.Mock
}

type MockTxContext_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockTxContext[T]) EXPECT() *MockTxContext_Expecter[T] {
	return &MockTxContext_Expecter[T]{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockTxContext
func (_mock *MockTxContext[T]) Commit() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxContext_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockTxContext_Commit_Call[T any] struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *MockTxContext_Expecter[T]) Commit() *MockTxContext_Commit_Call[T] {
	return &MockTxContext_Commit_Call[T]{Call: _e.mock.On("Commit")}
}

func (_c *MockTxContext_Commit_Call[T]) Run(run func()) *MockTxContext_Commit_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxContext_Commit_Call[T]) Return(err error) *MockTxContext_Commit_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxContext_Commit_Call[T]) RunAndReturn(run func() error) *MockTxContext_Commit_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Deadline provides a mock function for the type MockTxContext
func (_mock *MockTxContext[T]) Deadline() (time.Time, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Deadline")
	}

	var r0 time.Time
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (time.Time, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockTxContext_Deadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deadline'
type MockTxContext_Deadline_Call[T any] struct {
	*mock.Call
}

// Deadline is a helper method to define mock.On call
func (_e *MockTxContext_Expecter[T]) Deadline() *MockTxContext_Deadline_Call[T] {
	return &MockTxContext_Deadline_Call[T]{Call: _e.mock.On("Deadline")}
}

func (_c *MockTxContext_Deadline_Call[T]) Run(run func()) *MockTxContext_Deadline_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxContext_Deadline_Call[T]) Return(deadline time.Time, ok bool) *MockTxContext_Deadline_Call[T] {
	_c.Call.Return(deadline, ok)
	return _c
}

func (_c *MockTxContext_Deadline_Call[T]) RunAndReturn(run func() (time.Time, bool)) *MockTxContext_Deadline_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Done provides a mock function for the type MockTxContext
func (_mock *MockTxContext[T]) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockTxContext_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockTxContext_Done_Call[T any] struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockTxContext_Expecter[T]) Done() *MockTxContext_Done_Call[T] {
	return &MockTxContext_Done_Call[T]{Call: _e.mock.On("Done")}
}

func (_c *MockTxContext_Done_Call[T]) Run(run func()) *MockTxContext_Done_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxContext_Done_Call[T]) Return(valCh <-chan struct{}) *MockTxContext_Done_Call[T] {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockTxContext_Done_Call[T]) RunAndReturn(run func() <-chan struct{}) *MockTxContext_Done_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type MockTxContext
func (_mock *MockTxContext[T]) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxContext_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockTxContext_Err_Call[T any] struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockTxContext_Expecter[T]) Err() *MockTxContext_Err_Call[T] {
	return &MockTxContext_Err_Call[T]{Call: _e.mock.On("Err")}
}

func (_c *MockTxContext_Err_Call[T]) Run(run func()) *MockTxContext_Err_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxContext_Err_Call[T]) Return(err error) *MockTxContext_Err_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxContext_Err_Call[T]) RunAndReturn(run func() error) *MockTxContext_Err_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Executor provides a mock function for the type MockTxContext
func (_mock *MockTxContext[T]) Executor() T {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Executor")
	}

	var r0 T
	if returnFunc, ok := ret.Get(0).(func() T); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	return r0
}

// MockTxContext_Executor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Executor'
type MockTxContext_Executor_Call[T any] struct {
	*mock.Call
}

// Executor is a helper method to define mock.On call
func (_e *MockTxContext_Expecter[T]) Executor() *MockTxContext_Executor_Call[T] {
	return &MockTxContext_Executor_Call[T]{Call: _e.mock.On("Executor")}
}

func (_c *MockTxContext_Executor_Call[T]) Run(run func()) *MockTxContext_Executor_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxContext_Executor_Call[T]) Return(v T) *MockTxContext_Executor_Call[T] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockTxContext_Executor_Call[T]) RunAndReturn(run func() T) *MockTxContext_Executor_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockTxContext
func (_mock *MockTxContext[T]) Rollback() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxContext_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockTxContext_Rollback_Call[T any] struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *MockTxContext_Expecter[T]) Rollback() *MockTxContext_Rollback_Call[T] {
	return &MockTxContext_Rollback_Call[T]{Call: _e.mock.On("Rollback")}
}

func (_c *MockTxContext_Rollback_Call[T]) Run(run func()) *MockTxContext_Rollback_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxContext_Rollback_Call[T]) Return(err error) *MockTxContext_Rollback_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxContext_Rollback_Call[T]) RunAndReturn(run func() error) *MockTxContext_Rollback_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Value provides a mock function for the type MockTxContext
func (_mock *MockTxContext[T]) Value(key any) any {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func(any) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockTxContext_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type MockTxContext_Value_Call[T any] struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
//   - key any
func (_e *MockTxContext_Expecter[T]) Value(key interface{}) *MockTxContext_Value_Call[T] {
	return &MockTxContext_Value_Call[T]{Call: _e.mock.On("Value", key)}
}

func (_c *MockTxContext_Value_Call[T]) Run(run func(key any)) *MockTxContext_Value_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTxContext_Value_Call[T]) Return(v any) *MockTxContext_Value_Call[T] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockTxContext_Value_Call[T]) RunAndReturn(run func(key any) any) *MockTxContext_Value_Call[T] {
	_c.Call.Return(run)
	return _c
}
