// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package data

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTxManager creates a new instance of MockTxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxManager[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxManager[T] {
	mock := &MockTxManager[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxManager is an autogenerated mock type for the TxManager type
type MockTxManager[T any] struct {
	mock.Mock
}

type MockTxManager_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockTxManager[T]) EXPECT() *MockTxManager_Expecter[T] {
	return &MockTxManager_Expecter[T]{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockTxManager
func (_mock *MockTxManager[T]) Begin(ctx context.Context, opt ...TxOption) (TxContext[T], error) {
	var tmpRet mock.Arguments
	if len(opt) > 0 {
		tmpRet = _mock.Called(ctx, opt)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 TxContext[T]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...TxOption) (TxContext[T], error)); ok {
		return returnFunc(ctx, opt...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...TxOption) TxContext[T]); ok {
		r0 = returnFunc(ctx, opt...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TxContext[T])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...TxOption) error); ok {
		r1 = returnFunc(ctx, opt...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTxManager_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockTxManager_Begin_Call[T any] struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
//   - opt ...TxOption
func (_e *MockTxManager_Expecter[T]) Begin(ctx interface{}, opt ...interface{}) *MockTxManager_Begin_Call[T] {
	return &MockTxManager_Begin_Call[T]{Call: _e.mock.On("Begin",
		append([]interface{}{ctx}, opt...)...)}
}

func (_c *MockTxManager_Begin_Call[T]) Run(run func(ctx context.Context, opt ...TxOption)) *MockTxManager_Begin_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []TxOption
		var variadicArgs []TxOption
		if len(args) > 1 {
			variadicArgs = args[1].([]TxOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTxManager_Begin_Call[T]) Return(txContext TxContext[T], err error) *MockTxManager_Begin_Call[T] {
	_c.Call.Return(txContext, err)
	return _c
}

func (_c *MockTxManager_Begin_Call[T]) RunAndReturn(run func(ctx context.Context, opt ...TxOption) (TxContext[T], error)) *MockTxManager_Begin_Call[T] {
	_c.Call.Return(run)
	return _c
}
